### PR TITLE
Fix check for macos major version

### PR DESCRIPTION
**Pull request by andrewwhitehead**

### CODE REVIEW

**Comment by swcurran** [comment]
I gather this didn’t fix the issue?

**Comment by cvarjao** [comment]
Switching to `macos-12` get us back to a working pipeline. Maybe in a separate PR, we should still review compatibility with macos 14.

Changes:
https://github.com/hyperledger/indy-vdr/compare/main...cvarjao-o:indy-vdr:fix-cd?expand=1

Execution:
https://github.com/cvarjao-o/indy-vdr/actions/runs/9259858312

**Comment by andrewwhitehead** [comment]
Pinning `cc` to 1.0.83 seems to help the Darwin build on 14.x. I'm not sure if the exact issue has been reported but there are some potentially related cross compilation issues.

There's still an error in the iOS build occurring with cc pinned. In particular, this command seems to mix different architectures:

`/usr/bin/clang   -fPIC --target=x86_64-apple-ios -m64 -mios-simulator-version-min=7.0 -isysroot /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk -fembed-bitcode  -arch arm64 -MD -MT CMakeFiles/cmTC_e5ae3.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_e5ae3.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_e5ae3.dir/testCCompiler.c.o -c /Users/runner/work/indy-vdr/indy-vdr/target/x86_64-apple-ios/release/build/zmq-sys-cb80815203982fd7/out/build/CMakeFiles/CMakeScratch/TryCompile-YFxGth/testCCompiler.c`

I'm going to limit this PR to just fixing the minor version detection issue in `build-universal.sh`.

**Comment by andrewwhitehead** [comment]
@cvarjao Could you create a PR for your changes

**Comment by cvarjao** [comment]
Sure thing, here it is:
- #292

**Pull request merged**
