### PR TITLE
Added rust methods to build FREEZE_LEDGER and GET_FROZEN_LEDGER_REQUESTS

### PR DESCRIPTION
**Pull request by Artemkaaas**
Updated `Request Builder` to provide methods for building `FREEZE_LEDGER` and `GET_FROZEN_LEDGER_REQUESTS` requests. 
Currently, methods are only available in RUST API because it seems that Ledger Admin specific methods are not exposed in C / wrappers API.

### CODE REVIEW

**Comment by Artemkaaas** [comment]
@andrewwhitehead @WadeBarnes  Could take a look?

**Comment by andrewwhitehead** [comment]
> it seems that Ledger Admin specific methods are not exposed in C / wrappers API

What other methods did you have in mind?

**Review by andrewwhitehead — APPROVED** [review]

**Comment by Artemkaaas** [comment]
Here is the list of the methods I found: 
```
build_node_request
build_pool_config
build_pool_restart
build_auth_rule_request
build_auth_rules_request
build_get_auth_rule_request
build_ledger_freeze_request
build_get_frozen_ledgers_request
```

**Comment by andrewwhitehead** [comment]
Superseded by #137

**Pull request closed without merging**
