### PR TITLE
build(iOS): add CI/CD

### LINKED ISSUE #122: Fix iOS build for Indy VDR

### PR DESCRIPTION
**Pull request by blu3beri**
closes #122 

- Adds the build pipeline for the iOS libraries
- Creates an xcframework 

Work funded by the Government of Ontario.

### CODE REVIEW

**Review by TimoGlastra — DISMISSED** [review]
Nice 👍 

Will you add the ci script to add it to the github release so it can be downloaded using node-pre-gyp in a separate PR?

**Comment by blu3beri** [comment]
> Will you add the ci script to add it to the github release so it can be downloaded using node-pre-gyp in a separate PR?

What do you mean exactly? I though you did the node-pre-gyp binary fetch code. Do you mean changing the paths inside the android/iOS folder?

**Comment by TimoGlastra** [comment]
The node-pre-gyp still needs to be fleshed out a bit for React Native.

For node we publish the binaries to the release, for react native I didn't add it yet. So we will need to combine the ios and android builds into a single tar and upload that to the github release so it can be downloaded afterwards.

Here's the snippet that I created, but wasn't able to fully test it because I couldn't get the ios / android builds working. What it does is the following:
1. download ios and android binaries from the workflow artifacts and combine them into a mobile directory
2. tar the mobile directory
3. upload the tar to the github release

Then node-pre-gyp can download a single tar that contains both the ios and android binaries, as you can only download one tar with node-pre-gyp

```yaml
  # This is mostly needed for React Native, where we want to download the iOS & Android build together
  create-ios-android-release-asset:
    name: Create iOS and Android Release Assets
    if: |
      (github.event_name == 'release' ||
        (github.event_name == 'workflow_dispatch' &&
          github.event.inputs.publish == 'true'))
    runs-on: ubuntu-latest
    needs:
      - create-ios-xcframework
      - create-android-library
    steps:
      - name: Fetch Android libraries
        uses: actions/download-artifact@v3
        with:
          name: android-libraries
          path: mobile/android

      - name: Fetch iOS Framework
        uses: actions/download-artifact@v3
        with:
          name: libindy_vdr.xcframework
          path: mobile/ios

      - uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: ./mobile
          outPath: "library-ios-android.tar.gz"

      - name: Add library artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: library-ios-android.tar.gz
          asset_name: "library-ios-android.tar.gz"
```

**Comment by blu3beri** [comment]
> The node-pre-gyp still needs to be fleshed out a bit for React Native.
> 
> For node we publish the binaries to the release, for react native I didn't add it yet. So we will need to combine the ios and android builds into a single tar and upload that to the github release so it can be downloaded afterwards.
> 
> Here's the snippet that I created, but wasn't able to fully test it because I couldn't get the ios / android builds working. What it does is the following:
> 
> 1. download ios and android binaries from the workflow artifacts and combine them into a mobile directory
> 2. tar the mobile directory
> 3. upload the tar to the github release
> 
> Then node-pre-gyp can download a single tar that contains both the ios and android binaries, as you can only download one tar with node-pre-gyp
> 
> ```yaml
>   # This is mostly needed for React Native, where we want to download the iOS & Android build together
>   create-ios-android-release-asset:
>     name: Create iOS and Android Release Assets
>     if: |
>       (github.event_name == 'release' ||
>         (github.event_name == 'workflow_dispatch' &&
>           github.event.inputs.publish == 'true'))
>     runs-on: ubuntu-latest
>     needs:
>       - create-ios-xcframework
>       - create-android-library
>     steps:
>       - name: Fetch Android libraries
>         uses: actions/download-artifact@v3
>         with:
>           name: android-libraries
>           path: mobile/android
> 
>       - name: Fetch iOS Framework
>         uses: actions/download-artifact@v3
>         with:
>           name: libindy_vdr.xcframework
>           path: mobile/ios
> 
>       - uses: a7ul/tar-action@v1.1.2
>         with:
>           command: c
>           files: ./mobile
>           outPath: "library-ios-android.tar.gz"
> 
>       - name: Add library artifacts to release
>         uses: svenstaro/upload-release-action@v2
>         with:
>           file: library-ios-android.tar.gz
>           asset_name: "library-ios-android.tar.gz"
> ```

I will do it in this PR.

**Review by TimoGlastra — APPROVED** [review]

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
