### PR TITLE
NodeJS: Add FFI support for more functions, add tests, refactor

### PR DESCRIPTION
**Pull request by Patrik-Stas**
Add NodeJS FFI for:

Requests:
- `indy_vdr_build_custom_request`
- `indy_vdr_build_nym_request`
- `indy_vdr_build_get_nym_request`
- `indy_vdr_request_get_body`
- `indy_vdr_build_get_validator_info_request`
- `indy_vdr_build_get_schema_request`

Pool:
- `indy_vdr_pool_submit_request`
- `indy_vdr_pool_get_status`
- `indy_vdr_pool_get_transactions`
- `indy_vdr_pool_close`

Utils:
- `indyVdrSetDefaultLogger`
- `indyVdrSetConfig`
- `indyVdrVersion`

Signed-off-by: Patrik Stas <patrik.stas@absa.africa>

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
@andrewwhitehead Do you know by a chance what's current status of taking storage and signing/verifying apart from libindy? As I was writing integration tests on some requests which require signatures (like `indy_vdr_build_get_validator_info_request `) so I wonder if I could use some smaller component other than libindy to generate these signatures.

**Comment by andrewwhitehead** [comment]
@Patrik-Stas You can sign a message with the `SignKey` struct in indy-utils: https://docs.rs/indy-utils/0.3.2/indy_utils/keys/index.html and verify with `VerKey`, although that crate doesn't include support for storage. I have a large PR pending here that makes indy-utils a dependency.

**Comment by Patrik-Stas** [comment]
@andrewwhitehead sounds good! In that case this PR is ready for review. I'll experiment with indy-utils (or wait for the PR you mentioned) later in separate PR.

**Comment by Patrik-Stas** [comment]
Added CI to run unit and integration tests on NodeJS wrapper. Is there something like hyperledger or sovrin npmjs organization so we could push the wrapper there as package?

**Comment by andrewwhitehead** [comment]
I think @ryjones is probably the one to ask about that. Are you finished with this PR?

**Comment by Patrik-Stas** [comment]
@andrewwhitehead yup

**Comment by ryjones** [comment]
Hi - reach out to me on chat or email and let's get you hooked up to npm. We can also discuss using github packages instead of NPM

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
