### PR TITLE
Added .net wrapper

### PR DESCRIPTION
**Pull request by CHempel-esatus**
Signed-off-by: Christopher Hempel <c.hempel@esatus.com>

### CODE REVIEW

**Comment by swcurran** [comment]
@CHempel-esatus — thanks for this.  The DCO is failing — can you fix that?  DCO - Developer Certificate of Origin - https://github.com/apps/dco. We have to have that fixed before we can merge this.  Let us know if you need help with that.

**Comment by CHempel-esatus** [comment]
@swcurran I will fix it.

**Comment by CHempel-esatus** [comment]
@swcurran DCO is fixed.

**Review by TimoGlastra — APPROVED** [review]
I don't have too much experience with wrappers in .NET, but it seems there's test so I'm approving this PR 👍 

Did you update the PR with all the changes related to did:indy that have been applied?

Would be good to also set up some CI so it becomes just as easy to deploy the .NET wrapper as it is for the JS/Python wrappers

**Comment by swcurran** [comment]
@CHempel-esatus -- do you plan to move this forward?  Unfortunately, I can't update the PR to merge in the latest main branch updates, so can't move this forward.

I'll close the PR with this note, but would be fine if you want to reopen it and move it forward.

**Pull request closed without merging**
